@baseUrl = https://localhost:3000

###
# @name all
GET {{baseUrl}}/api/exam/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxNzMxNGY4LTkxMGEtNDFiZS05ZjJkLTg1MWNlNWMwOTYzYiIsImlhdCI6MTczMzIyODU0MCwiZXhwIjoxNzMzMjcxNzQwfQ.fu30Z2ueOh9HRgwyq7d3BL2JIrAqoMC2dPPBHJ_a6jM

###

@year = 2024
@position = "3"
@level   = "high"
@bankName = "ifrn"
@instituteName = "mrv"

# @name create
POST {{baseUrl}}/api/exam/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxNzMxNGY4LTkxMGEtNDFiZS05ZjJkLTg1MWNlNWMwOTYzYiIsImlhdCI6MTczMzIyODU0MCwiZXhwIjoxNzMzMjcxNzQwfQ.fu30Z2ueOh9HRgwyq7d3BL2JIrAqoMC2dPPBHJ_a6jM

{
    "year": {{year}},
    "position": {{position}},
    "level" : {{level}},
    "bankName" : {{bankName}},
    "instituteName" : {{instituteName}}
}
