@baseUrl = https://localhost:3000

###
@email= "teste01@gmail.com"
@name = "salve jorge"
@password = "password"
@role = "admin"
@birthDate = "2003-01-01"


# @name createUser

POST {{baseUrl}}/api/user/create HTTP/1.1
Content-Type: application/json

{
    "email": {{email}},
    "password": {{password}},
    "name" : {{name}},
    "role" : {{role}},
    "birthDate" : {{birthDate}}
}

###
# @name all
GET {{baseUrl}}/api/user/all HTTP/1.1
Content-Type: application/json


###

# @name delete
@idUser = e7fe4550-8631-4629-ab92-8c6766c50bc8

DELETE {{baseUrl}}/api/user/delete/{{idUser}} HTTP/1.1
Content-Type: application/json

